CREATE TABLE ScrappTest (
	id_config INTEGER PRIMARY KEY AUTOINCREMENT,
	parent_tag VARCHAR(255) NOT NULL,
    title_tag VARCHAR(255) NOT NULL,
    img_tag VARCHAR(255) NOT NULL,
    price_tag VARCHAR(255) NOT NULL,
    url_tag VARCHAR(255),
    url_attribute VARCHAR(255),
    url_base VARCHAR(255),
    url_class VARCHAR(255),
    url_test VARCHAR(255),
    price_parent_tag VARCHAR(255),
    price_parent_class VARCHAR(255),
    price_code VARCHAR(255),
    price_integer VARCHAR(255),
    price_decimal VARCHAR(255),
    price_fraction VARCHAR(255),
    img_attribute VARCHAR(255),
    parent_class VARCHAR(255),
    title_class VARCHAR(255),
    price_class VARCHAR(255),
    img_class VARCHAR(255),
    alt_price_parent_tag VARCHAR(255),
    alt_price_parent_class VARCHAR(255),
    alt_img_tag VARCHAR(255),
    alt_img_class VARCHAR(255),
    alt_parent_class_2 VARCHAR(255),
    alt_img_tag_2 VARCHAR(255),
    alt_img_class_2 VARCHAR(255),
    alt_parent_tag_2 VARCHAR(255),
    alt_parent_tag VARCHAR(255),
    alt_parent_class VARCHAR(255)
);